Modified readme, added more parameters for run command

diff --git a/run/tv/run b/run/tv/run
--- a/run/tv/run
+++ b/run/tv/run
@@ -5,6 +5,7 @@ set -e
 # Tester image
 # Contains PTF and tvutils libraries, as well as P4RT, gNMI, and TV Python bindings
 TESTER_DOCKER_IMG=stratumproject/testvectors:ptf
+SDE_VERSION=${SDE_VERSION:-9.0.0}
 
 DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" > /dev/null 2>&1 && pwd)"
 ROOT_DIR=${DIR}/../..
@@ -17,6 +18,27 @@ if [[ -z "${FABRIC_TOFINO}" ]]; then
     echo "ERROR: FABRIC_TOFINO env not defined"
     exit 1
 fi
+if [[ -z "${SDE_VERSION}" ]]; then
+    echo "ERROR: SDE_VERSION env not defined"
+    exit 1
+fi
+fabricProfile=$1
+if [ -z "${fabricProfile}" ]; then
+    echo "fabric profile is not set"
+    exit 1
+fi
+
+# Find Tofino compiled artifacts
+sdeVer_=$(echo "${SDE_VERSION}" | tr . _) # Replace dots with underscores
+TOFINO_P4C_OUT=${FABRIC_TOFINO}/src/main/resources/p4c-out/${fabricProfile}/tofino/mavericks_sde_${sdeVer_}
+echo "*** Using P4 compiler output in ${TOFINO_P4C_OUT}..."
+if [ ! -f "${TOFINO_P4C_OUT}"/pipe/tofino.bin ]; then
+    echo "ERROR: missing tofino.bin in ${TOFINO_P4C_OUT}"
+    exit 1
+fi
+
+# BMv2 compiled artifacts
+BMV2_P4C_OUT=${ONOS_ROOT}/pipelines/fabric/impl/src/main/resources/p4c-out/${fabricProfile}/bmv2/default
 
 # Clean up old logs (if any)
 rm -rf "${DIR}"/log
@@ -32,7 +54,7 @@ echo "*** Starting ${testerRunName}..."
 it=$(test -t 0 && echo "-it" || echo "-t")
 docker run --name ${testerRunName} ${it} --privileged --rm \
     -v "${ROOT_DIR}":/fabric-p4test \
-    -v "${ONOS_ROOT}":/onos -e ONOS_ROOT=/onos \
-    -v "${FABRIC_TOFINO}":/fabric-tofino -e FABRIC_TOFINO=/fabric-tofino \
+    -v "${BMV2_P4C_OUT}":/bmv2_p4c_out \
+    -v "${TOFINO_P4C_OUT}":/tofino_p4c_out \
     "${TESTER_DOCKER_IMG}" \
     bash /fabric-p4test/run/tv/start_test.sh "${FABRIC_PROFILE}" ${@}
